on: [push]
jobs:
  run-and-compile-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt install g++
      - run: chmod +x build.sh
      - run: ./build.sh
  run-and-compile-windows:
    runs-on: windows-latest
    steps:
        - name: Setup MSVC Developer Command Prompt
          uses: TheMrMilchmann/setup-msvc-dev@v3.0.0
          with:
            arch: x64
        - uses: actions/checkout@v4
        - run: call build.bat
          shell: cmd